name: Deploy to Heroku

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
        env:
          HD_NODE_ENV: "production"
          HD_SESSION_SECRET: ${{ secrets.HEROKU_APPLICATION_SESSION_SECRET }}
          HD_DB_CONNECTION_STRING: ${{ secrets.HEROKU_APPLICATION_DB_CONNECTION_STRING }}
          HD_LOG_FORMAT_MORGAN: "tiny"
          HD_APP_NAME: "Customer Request Management System"
          HD_APP_URL: ${{ secrets.HEROKU_APPLICATION_URL }}